#########################################
# CONFIGURATION OF TOR CONTAINER
#########################################

#
# USE TOR BRIDGES
#
# To get Tor bridges head over to https://bridges.torproject.org and click on
# Get bridges, then you will see a form with "Advanced Options" header
# leave the Pluggable Transport as obfs4 and click on Get Bridges button
# solve the captcah, you will get the bridge addresses (usually 3)
#
# Then, set TOR_USE_BRIDGES to "on" and initialize the TOR_BRIDGE_n options
# with the 3 lines generated by the online tool.
#
# For instance, if the first line generated by the tool is:
#   obfs4 24.106.248.94:65531 B9EFBC5... cert=yrX... iat-mode=0
# You will have to set:
#   TOR_BRIDGE_1=obfs4 24.106.248.94:65531 B9EFBC5... cert=yrX... iat-mode=0
#


# Activate the use of Tor bridges
# Value: on | off
TOR_USE_BRIDGES=off

# Bridge 1
TOR_BRIDGE_1=ToBeDefined

# Bridge 2
TOR_BRIDGE_2=ToBeDefined

# Bridge 3
TOR_BRIDGE_3=ToBeDefined
